import { useEffect, useState } from 'react';
import { api } from '../../lib/api.js';
import { WHITELABEL, salesProjection } from '../../../shared/whitelabel.js';
import { money } from '../../../shared/pricing.js';
import './Whitelabel.css';

export default function Whitelabel() {
 const [requestKey]=useState(()=>{let key=sessionStorage.getItem('kidora_whitelabel_request');if(!key){key=crypto.randomUUID();sessionStorage.setItem('kidora_whitelabel_request',key);}return key;});
 const [offer,setOffer]=useState(null);
 useEffect(()=>{api('/whitelabel/offer').then(setOffer).catch(()=>setOffer(null));const oldTitle=document.title;document.title='Whitelabel Kidora — Brand Sendiri | RM897 Setahun';return()=>{document.title=oldTitle;};},[]);
 const [price,setPrice]=useState(2990),[sales,setSales]=useState(50),[cost,setCost]=useState(0),[fixed,setFixed]=useState(0);
 const [form,setForm]=useState({name:'',email:'',phone:''}),[agreed,setAgreed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const result=salesProjection(price,sales,cost,fixed);
 const checkout=async e=>{e.preventDefault();setError('');if(!WHITELABEL.ready||!offer?.available){setError('Slot belum tersedia. Sila muat semula atau hubungi kami untuk semakan.');return;}setBusy(true);try{const data=await api('/order',{method:'POST',body:JSON.stringify({...form,package:'whitelabel',requestKey,termsVersion:WHITELABEL.termsVersion,acceptedTerms:agreed})});if(!data.url||!/^https:\/\//i.test(data.url))throw new Error('Pautan pembayaran tidak tersedia. Sila cuba lagi.');window.location.assign(data.url);}catch(e){setError(e.message);setBusy(false);}};
 const cta=(label='Bina brand saya — RM897')=><a className="wl-button" href="#daftar">{label}<span aria-hidden="true">↗</span></a>;
 return <div className="wl">
 <nav className="wl-nav"><a href="https://kidora.com.my" className="wl-logo">KIDORA<span>WHITELABEL</span></a><a href="#simulasi" className="wl-nav-link">Kira potensi jualan</a>{cta('Dapatkan tawaran')}</nav>
 {!WHITELABEL.ready&&<div className="wl-draft">PRATONTON TAWARAN · Butiran pakej, kelayakan jaminan dan had pengambilan menunggu pengesahan.</div>}
 <main>
 <section className="wl-hero wl-section"><div><div className="wl-eyebrow">UNTUK USAHAWAN YANG MAHU JENAMA SENDIRI</div><h1>Produk pendidikan.<br/>Peluang bisnes.<br/><em>Nama brand anda.</em></h1><p className="wl-lead">Bina tawaran pendidikan kanak-kanak di bawah jenama sendiri melalui pakej whitelabel Kidora, dengan tunjuk ajar untuk membantu anda memulakan jualan.</p><div className="wl-price"><del>RM2,990</del><span>DISKAUN 70%</span><strong>RM897<small>setahun</small></strong></div>{cta()}<p className="wl-micro">Jimat RM2,093 · Pembaharuan RM897 setahun · 10 slot terawal</p></div>
 <div className="wl-brand-card"><div className="wl-card-top"><span>IDEA ANDA. IDENTITI ANDA.</span><i>CONTOH VISUAL</i></div><div className="wl-brand-icon">Aa<span>★</span></div><h2>Brand Anda<span>Belajar bermula dengan bermain.</span></h2><div className="wl-mini-grid"><div>ABC<small>Kenal huruf</small></div><div>123<small>Kenal nombor</small></div><div>✦<small>Belajar sambil main</small></div></div><div className="wl-card-note">Daripada berkongsi produk orang lain<br/><strong>kepada memperkenalkan jenama sendiri.</strong></div></div></section>
 <section className="wl-strip"><span>01 · Jenama sendiri</span><span>02 · Produk pendidikan</span><span>03 · Tunjuk ajar jualan</span><span>04 · Tetapkan harga sendiri</span></section>
 <section className="wl-section"><div className="wl-eyebrow">KENAPA WHITELABEL?</div><h2>Jadikan produk sebagai asas.<br/>Bina nilai melalui jenama anda.</h2><p className="wl-section-intro">Whitelabel sesuai untuk anda yang mahu memasarkan tawaran dengan identiti sendiri, membina hubungan dengan pelanggan dan mengembangkan cara jualan anda.</p><div className="wl-benefits"><article><b>01</b><h3>Identiti yang pelanggan ingat</h3><p>Perkenalkan jenama anda sendiri dalam tawaran pendidikan. Nama dan pendekatan pemasaran menjadi sebahagian daripada pengalaman pelanggan.</p></article><article><b>02</b><h3>Harga jualan dalam kawalan anda</h3><p>Klien whitelabel bebas menetapkan harga jualan sendiri. Bina tawaran mengikut sasaran pelanggan, kos dan margin yang anda mahukan.</p></article><article><b>03</b><h3>Mula dengan tunjuk ajar</h3><p>Ikuti coaching 1-to-1 secara atas talian atau bersemuka untuk strategi jualan dan penggunaan sistem. Hasil tetap bergantung pada pelaksanaan, permintaan dan kos pemasaran anda.</p></article></div></section>
 <section className="wl-section wl-offer" id="pakej"><div><div className="wl-eyebrow">SATU LANGKAH UNTUK BERMULA</div><h2>Bukan sekadar idea.<br/>Mulakan tawaran jenama anda.</h2><p>Logo dan jenama sendiri, domain, hosting, akses sistem, pemasangan pembayaran serta tunjuk ajar disatukan dalam satu pakej tahunan. Anda boleh menumpukan usaha kepada memperkenalkan jenama dan mencari pelanggan.</p><a href="https://kidora.com.my" className="wl-text-link">Lihat pengalaman produk Kidora ↗</a></div><div className="wl-offer-box"><h3>Pakej Whitelabel</h3><ul><li>Logo dan penjenamaan sendiri</li><li>Domain untuk jenama anda</li><li>Hosting bagi tempoh setahun</li><li>Akses sistem whitelabel</li><li>Bebas menetapkan harga jualan sendiri</li><li>Pemasangan sistem pembayaran</li><li>Coaching 1-to-1: strategi jualan dan penggunaan sistem</li></ul><p className="wl-availability">RM897 setahun termasuk penyelenggaraan domain dan hosting. Pembaharuan tahun berikutnya kekal RM897 setahun dan dibuat secara manual; tiada debit berulang automatik.</p><div className="wl-offer-total"><span>Harga tawaran</span><strong>RM897</strong></div>{cta()}</div></section>
 <section className="wl-section" id="simulasi"><div className="wl-eyebrow">LIHAT ANGKA. BUAT PERTIMBANGAN SENDIRI.</div><h2>Berapa jualan untuk<br/>menampung kos pakej?</h2><p className="wl-section-intro">Pada harga contoh RM29.90, 30 jualan menghasilkan RM897 jualan kasar. Itu menyamai harga pakej sebelum mengambil kira sebarang kos lain.</p><div className="wl-calculator"><div className="wl-controls"><h3>Simulasi bisnes anda</h3><label>Harga jualan anda (RM)<input type="number" min="0.01" max="10000" step="0.01" value={price/100} onChange={e=>setPrice(Math.max(0,Math.round(Number(e.target.value)*100)))}/></label><label>Sasaran pembelian <strong>{sales}</strong><input type="range" min="0" max="300" step="1" value={sales} onChange={e=>setSales(Number(e.target.value))}/></label><div className="wl-costs"><label>Kos setiap jualan (RM)<input type="number" min="0" max="10000" step="0.01" value={cost/100} onChange={e=>setCost(Math.max(0,Math.round(Number(e.target.value)*100)))}/></label><label>Kos lain tahun pertama (RM)<input type="number" min="0" max="100000" step="0.01" value={fixed/100} onChange={e=>setFixed(Math.max(0,Math.round(Number(e.target.value)*100)))}/></label></div><small>Masukkan fee bayaran, komisyen, iklan, domain, hosting dan kos lain yang berkenaan. Domain, hosting dan penyelenggaraan tahun pertama termasuk dalam RM897. Nilai awal RM0 bagi kos tambahan ialah andaian simulasi, bukan pengesahan bahawa pemasaran dan transaksi percuma.</small></div><div className="wl-results"><span>JUALAN KASAR</span><strong>{money(result.revenueCents)}</strong><div><span>Pakej + kos yang dimasukkan</span><b>{money(result.costsCents)}</b></div><div><span>Baki selepas kos dimasukkan</span><b className={result.balanceCents<0?'wl-negative':''}>{money(result.balanceCents)}</b></div><div className="wl-break-even"><b>{result.breakEven===null?'Tidak tercapai':`${result.breakEven} jualan`}</b><span>untuk menampung kos pakej dan kos yang dimasukkan</span></div><small>Contoh pengiraan sahaja, bukan ramalan atau jaminan pendapatan. Baki ini belum mengambil kira kos yang tidak dimasukkan dan cukai.</small></div></div>
 <div className="wl-scenarios">{[30,50,100].map(n=><article key={n}><span>{n} pembelian × RM29.90</span><strong>{money(n*2990)}</strong><small>jualan kasar, bukan untung bersih</small></article>)}</div></section>
 <section className="wl-guarantee wl-section" id="jaminan"><div className="wl-shield">✓</div><div><div className="wl-eyebrow">KOMITMEN SYARIKAT</div><h2>Money-back guarantee.<br/>Dengan syarat yang jelas.</h2><p>Jika anda tidak berjaya membuat jualan selepas diberikan tunjuk ajar, syarikat menawarkan jaminan wang dikembalikan, tertakluk pada pematuhan terma dan syarat.</p><div className="wl-guarantee-terms">Dalam 30 hari dari tarikh pembayaran berjaya, hadiri sesi coaching 1-to-1 secara atas talian atau bersemuka mengenai strategi jualan dan penggunaan sistem. Jika masih tiada jualan selepas sesi tersebut, anda boleh memohon bayaran balik harga pakej RM897 dalam tempoh 30 hari tersebut.</div><ul className="wl-terms-list"><li>Syarat kelayakan: sesi coaching telah dihadiri dan tiada jualan diperoleh selepas coaching.</li><li>Hubungi <a href="https://wa.me/60183577910">sokongan WhatsApp</a> sebelum tamat hari ke-30 dengan rujukan pesanan, rekod sesi coaching dan rekod jualan sistem untuk semakan.</li><li>Bayaran balik meliputi RM897 harga pakej yang dibayar, selepas kelayakan disahkan. Kos luar seperti iklan tidak termasuk.</li><li>Pengaktifan dan sesi coaching diselaraskan selepas pembayaran. Hubungi sokongan awal untuk menetapkan sesi dalam tempoh jaminan.</li></ul><p className="wl-micro">Jaminan ini bukan janji pendapatan. Tiada syarat tambahan seperti belanja iklan minimum ditetapkan dalam tawaran ini.</p></div></section>
 <section className="wl-section"><div className="wl-eyebrow">DARI MINAT KEPADA TINDAKAN</div><h2>Perjalanan anda bermula di sini.</h2><div className="wl-benefits"><article><b>01</b><h3>Semak tawaran</h3><p>Fahami skop whitelabel, kos berkaitan dan syarat jaminan.</p></article><article><b>02</b><h3>Buat pembayaran</h3><p>Bayar harga tawaran RM897 melalui halaman pembayaran Bayarcash.</p></article><article><b>03</b><h3>Mulakan dengan bimbingan</h3><p>Selesaikan maklumat jenama dan ikuti langkah tunjuk ajar yang disediakan.</p></article></div></section>
 <section className="wl-section wl-checkout" id="daftar"><div><div className="wl-eyebrow">MULA MEMBINA JENAMA ANDA</div><h2>Ambil langkah pertama.<br/><em>Bina brand sendiri.</em></h2><p>Pakej whitelabel tahun pertama pada harga RM897, berbanding harga asal RM2,990. Semak butiran dan terma, kemudian teruskan ke pembayaran.</p><div className="wl-price"><del>RM2,990</del><span>JIMAT RM2,093</span><strong>RM897<small>setahun</small></strong></div><p className="wl-availability">Pengambilan ini terhad kepada 10 slot terawal. Slot ditempah semasa pembayaran disediakan dan disahkan selepas bayaran berjaya.</p></div><form onSubmit={checkout}><h3>Daftar pakej whitelabel</h3><div className="wl-availability" aria-live="polite">{offer ? (offer.available ? `${offer.remainingSlots} slot tersedia untuk ditempah` : 'Semua slot sedang ditempah atau telah disahkan. Hubungi kami untuk semakan.') : 'Sedang menyemak ketersediaan slot…'}</div><label>Nama penuh<input required minLength={5} maxLength={100} autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Emel<input required type="email" maxLength={254} autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Nombor telefon<input required type="tel" maxLength={24} autoComplete="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="wl-consent"><input type="checkbox" required checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>Saya faham harga RM897 setahun, pembaharuan RM897 setahun, skop pakej dan <a href="#jaminan">syarat jaminan 30 hari</a>.</span></label>{error&&<p className="wl-error" role="alert">{error}</p>}<button className="wl-button" disabled={busy||!WHITELABEL.ready||!offer?.available}>{busy?'Menyediakan pembayaran…':'Terus bayar RM897 — 1 tahun'}<span>↗</span></button><small>Bayaran tahun pertama melalui Bayarcash. Selepas pembayaran disahkan, pasukan akan menyelaraskan maklumat jenama, pemasangan dan sesi coaching.</small></form></section>
 </main><footer className="wl-footer"><a className="wl-logo" href="https://kidora.com.my">KIDORA<span>WHITELABEL</span></a><span>Jenama anda. Langkah anda. Potensi untuk dibina.</span><a href="https://kidora.com.my/privasi">Privasi</a><a href="https://wa.me/60183577910">Hubungi kami ↗</a></footer>
 </div>;
}
